kind: pipeline
name: default

workspace:
  base: /book
  path: art

steps:
- name: build
  image: panbook:latest
  pull: if-not-exists
  commands:
  - DEBUG=-d make build
 
- name: publish
  image: annprog/rsync:latest
  pull: if-not-exists
  settings:
    src: build/*.pdf
    dest: 172.17.0.1::panbook/ops-quiz/
  depends_on:
  - build